### ISSUE TITLE
Trying to get it to work on the GLES2 Backend.

### ISSUE THREAD

**Issue by MossFrog** [hgouveia/godot-toon-water-shader-port#2]
vec3 existingNormal = vec3(dFdx(depth), dFdy(depth), 0);
This line in the shader is incompatible with the GLES2 Backend, is there a way to replace it with something compatible?
I'm sure there is a more practical way to obtain the NORMAL from the camera.

**Comment by hgouveia** [comment]
@MossFrog unfortunately there is no way to obtain the NORMAL from the 3d Camera in Godot 3, for this shader i am trying to get the normals using the depth, however this will be possible with Godot 4, i will try to update it in the future, but of course will be only for Vulkan, 

you can try this function i just ported bases on https://theorangeduck.com/page/pure-depth-ssao , didnt try it with GLES2 yet, 

```
vec3 normal_from_depth(float depth, sampler2D depthTexture, vec2 texcoords) {
  
  const vec2 offset1 = vec2(0.0,0.001);
  const vec2 offset2 = vec2(0.001,0.0);
  
  float depth1 = texture(depthTexture, texcoords + offset1).r;
  float depth2 = texture(depthTexture, texcoords + offset2).r;
  
  vec3 p1 = vec3(offset1, depth1 - depth);
  vec3 p2 = vec3(offset2, depth2 - depth);
  
  vec3 normal = cross(p1, p2);
  normal.z = -normal.z;
  
  return normalize(normal);
}
```

then just replace `vec3 existingNormal = normal_from_depth(depth, DEPTH_TEXTURE, SCREEN_UV);` , if this still doesnt work for you, you can try to replace that line with `vec3 existingNormal = vec3(0,0,0);` and bypass this, it might work but probably you will get issue with lighting and reflection, but try it

**Comment by MossFrog** [comment]
Thank you will give it a go!
